### PR TITLE
added footers and fonts

### PR DESCRIPTION
**Pull request by Idadelveloper**

### CODE REVIEW

**Comment by XodTuza** [comment]
Please Dont merge this PR till you confirm from @Gordie

**Comment by Gordie** [comment]
Hi there,

I have recieved a few emails from you over night.. I am so sorry but I have
no idea what this is about..

Can you please advise..

Kind regards

Gordon

**Comment by Idadelveloper** [comment]
So my pull request is on me adding footers to all the pages of Group 4 and
embedding fonts in some of the pages.

**Comment by Gordie** [comment]
For what?

I have no idea what or why your contacting me.. what is this with regards
to?

I signed up for a Coursera course yesterday.. if this what this is about?

As I have had no information about groups or anything else regarding this..

Sorry for being so ignorant about it..lol

Regards

Gordon

**Comment by Idadelveloper** [comment]
Some one told me to not merge my pull request for the hng internship until
i confirm from Gordie

**Comment by Gordie** [comment]
So is this part of the coursera course?

**Comment by Idadelveloper** [comment]
Its okay. Seems like u got no clue...

**Comment by Gordie** [comment]
Is it part of the coursera course?

**Comment by Gordie** [comment]
Please remove me from your mailing list..

Thank you

**Pull request merged**
